### ISSUE TITLE
Multi-Tenancy Mini-Series

### ISSUE THREAD

**Issue by harrict** [myquay/michaelmckenna.com#1]
Michael - 

I was reading your blogs about multi-tenancy and had a question. With implementing the ServiceProviderFactory solution for .Net Core 3.1 the services are now registered in a static method in the StartUp class. How do you or would you handle registering something that requires IConfiguration settings. Since the method is static it can't access the Configuration property in StartUp and I'm not sure the best way then to implement this.

For example: I'm wanting to register a SeriLog logger to the tenant container as follows:
```
public static void ConfigureMultiTenantContainer(Tenant t, ContainerBuilder c)
{
            var tenantServices = new ServiceCollection();

            // configure logging
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(**StaticConfiguration**) // read from appsettings json
                .Enrich.WithExceptionDetails() 
                .WriteTo.MSSqlServer(t.DbConnectionString, schemaName: "dbo", tableName: "ApiLog")
                .CreateLogger();

            tenantServices.AddSingleton(typeof(Serilog.ILogger), Log.Logger); 

            c.Populate(tenantServices);
}
```

Thanks for any help you can provide!

**Comment by myquay** [comment]
Thanks for getting in touch! I can't help with this one sorry though.
