### ISSUE TITLE
TenantOptions don't work with auto-reload of configuration

### ISSUE THREAD

**Issue by kwaazaar** [myquay/michaelmckenna.com#2]
Related to this page: https://github.com/myquay/michaelmckenna.com/blob/main/blog/content/post/2019/multi-tenancy-in-asp-dot-net-core.2.md

I noticed the IOptionSnapshot never gets a new value after being cached with the initial data. IOptionsMonitor.CurrentValue is the same: always the initial value, never an update.

**Comment by myquay** [comment]
Thanks for letting me know! 

I've updated the post with a note saying the technique described doesn't support auto-reload.
